package postgresql

import (
	"github.com/Ndraaa15/Educode/internal/pkg/entity"
	"github.com/Ndraaa15/Educode/pkg/utils/bcrypt"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

func QuizSeed() []entity.Quiz {
	quizzes := []entity.Quiz{{
		ID:          1,
		Name:        "BAB 1 Informatika dan Keterampilan Generik",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652831/iquest/Rectangle_ddwqjn.png",
		Description: "Mempelajari tentang informatika dan keterampilan generik yang diperlukan dalam dunia digital.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   1,
				Question: "Apa definisi informatika?",
				OptionA:  "Bidang ilmu yang hanya berkaitan dengan komputer.",
				OptionB:  "Studi tentang sistem komputasi dan matematika.",
				OptionC:  "Ilmu yang tidak memerlukan pemodelan matematika.",
				OptionD:  "Ilmu yang tidak berubah selama lebih dari 20 tahun.",
				Answer:   "Studi tentang sistem komputasi dan matematika.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dimaksud dengan berpikir komputasional?",
				OptionA:  "Berpikir dengan bantuan komputer.",
				OptionB:  "Pemikiran yang hanya terkait dengan komputer.",
				OptionC:  "Proses berpikir yang mencakup perangkat keras dan perangkat lunak.",
				OptionD:  "Cara berpikir yang hanya berguna dalam dunia digital.",
				Answer:   "Proses berpikir yang mencakup perangkat keras dan perangkat lunak.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dimaksud dengan Industri 4.0?",
				OptionA:  "Era di mana manusia tidak lagi bekerja.",
				OptionB:  "Era di mana teknologi tidak diperlukan.",
				OptionC:  "Era di mana banyak pekerjaan dilakukan oleh manusia.",
				OptionD:  "Era di mana teknologi komputer dan internet berperan besar dalam kehidupan manusia.",
				Answer:   "Era di mana teknologi komputer dan internet berperan besar dalam kehidupan manusia.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dimaksud dengan \"society 5.0\"?",
				OptionA:  "Era di mana masyarakat tidak lagi berkomunikasi secara online.",
				OptionB:  "Era di mana masyarakat hanya berinteraksi di dunia nyata.",
				OptionC:  "Era di mana masyarakat hidup di dunia maya dan nyata secara bersamaan.",
				OptionD:  "Era di mana masyarakat hidup dalam isolasi total.",
				Answer:   "Era di mana masyarakat hidup di dunia maya dan nyata secara bersamaan.",
			},
			{
				QuizID:   1,
				Question: "Mengapa banyak pekerjaan manusia digantikan oleh teknologi komputer?",
				OptionA:  "Karena teknologi komputer tidak efisien.",
				OptionB:  "Karena teknologi komputer tidak dapat diandalkan.",
				OptionC:  "Karena teknologi komputer tidak ada dalam Industri 4.0.",
				OptionD:  "Karena teknologi komputer dapat melakukan pekerjaan rutin dengan lebih efisien.",
				Answer:   "Karena teknologi komputer dapat melakukan pekerjaan rutin dengan lebih efisien.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dimaksud dengan karakteristik profil pelajar Pancasila?",
				OptionA:  "Berpikir kritis dan kreatif.",
				OptionB:  "Tidak memiliki karakteristik tertentu.",
				OptionC:  "Tidak memiliki kepercayaan kepada Tuhan.",
				OptionD:  "Tidak berinteraksi dengan teman-teman.",
				Answer:   "Berpikir kritis dan kreatif.",
			},
			{
				QuizID:   1,
				Question: "Mengapa siswa SMA perlu membangun karakter profil pelajar Pancasila?",
				OptionA:  "Karena mereka tidak perlu memiliki karakteristik tertentu.",
				OptionB:  "Karena mereka tidak akan berkarir di bidang komputer.",
				OptionC:  "Karena karakteristik tersebut hanya berlaku di dunia nyata.",
				OptionD:  "Karena karakteristik tersebut membantu mereka dalam kehidupan nyata dan digital.",
				Answer:   "Karena karakteristik tersebut membantu mereka dalam kehidupan nyata dan digital.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dipelajari dalam mata pelajaran informatika?",
				OptionA:  "Hanya pemrograman komputer.",
				OptionB:  "Hanya teori-teori informatika.",
				OptionC:  "Prinsip-prinsip ilmiah yang tidak berhubungan dengan dunia nyata.",
				OptionD:  "Berpikir komputasional dan aplikasi teknologi komputer dalam berbagai bidang.",
				Answer:   "Berpikir komputasional dan aplikasi teknologi komputer dalam berbagai bidang.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dimaksud dengan \"surprise\" dalam konteks informatika?",
				OptionA:  "Kejutan yang tidak diinginkan.",
				OptionB:  "Hasil yang tidak memuaskan.",
				OptionC:  "Kejutan karena produk informatika menghasilkan sesuatu yang dapat diamati dan berfungsi dengan baik.",
				OptionD:  "Hasil yang tidak berguna.",
				Answer:   "Kejutan karena produk informatika menghasilkan sesuatu yang dapat diamati dan berfungsi dengan baik.",
			},
			{
				QuizID:   1,
				Question: "Mengapa penting bagi siswa SMA untuk mempelajari informatika?",
				OptionA:  "Karena mereka harus menjadi ahli komputer.",
				OptionB:  "Karena mereka harus mengisolasi diri dari teknologi komputer.",
				OptionC:  "Karena mereka hanya akan menggunakan teknologi komputer dalam pekerjaan mereka.",
				OptionD:  "Karena mereka perlu memahami dan mengaplikasikan teknologi komputer dalam berbagai bidang.",
				Answer:   "Karena mereka perlu memahami dan mengaplikasikan teknologi komputer dalam berbagai bidang.",
			},
			{
				QuizID:   1,
				Question: "Apa yang dimaksud dengan kolaborasi dalam konteks informatika?",
				OptionA:  "Proses mengerjakan tugas seorang diri.",
				OptionB:  "Proses bekerja sama dengan satu orang lain.",
				OptionC:  "Proses dua orang atau lebih bekerja sama untuk menyelesaikan tugas atau mencapai tujuan.",
				OptionD:  "Proses membagi tugas kepada semua anggota kelompok.",
				Answer:   "Proses dua orang atau lebih bekerja sama untuk menyelesaikan tugas atau mencapai tujuan.",
			},
			{
				QuizID:   1,
				Question: "Apa yang diperlukan untuk kolaborasi yang baik dalam kelompok?",
				OptionA:  "Kepemimpinan yang dominan.",
				OptionB:  "Pembagian tugas yang tidak adil.",
				OptionC:  "Peran yang tidak jelas.",
				OptionD:  "Komunikasi yang buruk antar anggota kelompok.",
				Answer:   "Komunikasi yang buruk antar anggota kelompok.",
			},
			{
				QuizID:   1,
				Question: "Mengapa kolaborasi dalam tim dianggap penting dalam informatika?",
				OptionA:  "Karena kolaborasi hanya menghambat proses kerja.",
				OptionB:  "Karena tugas informatika biasanya bisa diselesaikan oleh satu orang.",
				OptionC:  "Karena kolaborasi mempercepat proses menyelesaikan tugas yang lebih besar.",
				OptionD:  "Karena kolaborasi hanya diperlukan di dunia digital.",
				Answer:   "Karena kolaborasi mempercepat proses menyelesaikan tugas yang lebih besar.",
			},
			{
				QuizID:   1,
				Question: "Apa yang bisa dihasilkan dari kerja kelompok dalam kolaborasi?",
				OptionA:  "Hanya satu solusi dari satu sudut pandang.",
				OptionB:  "Alternatif solusi dari berbagai sudut pandang.",
				OptionC:  "Solusi yang diimplementasikan tanpa demokrasi.",
				OptionD:  "Solusi yang lambat dalam menyelesaikan tugas.",
				Answer:   "Alternatif solusi dari berbagai sudut pandang.",
			},
			{
				QuizID:   1,
				Question: "Kapan kolaborasi dalam kelompok tidak selalu membuat tugas lebih cepat selesai?",
				OptionA:  "Saat masing-masing anggota kelompok dapat mengerjakan tugas secara mandiri.",
				OptionB:  "Saat tugas yang dikerjakan oleh lebih banyak orang memerlukan koordinasi yang rumit.",
				OptionC:  "Saat tugas hanya dapat dibagi dengan mudah.",
				OptionD:  "Saat jumlah anggota kelompok tidak sesuai dengan tugas yang diberikan.",
				Answer:   "Saat tugas yang dikerjakan oleh lebih banyak orang memerlukan koordinasi yang rumit.",
			},
			{
				QuizID:   1,
				Question: "Berikut hal-hal yang perlu diperhatikan dalam membuat tampilan infografis, kecuali ...",
				OptionA:  "Pemilihan kata kunci",
				OptionB:  "Tata warna dan tata letak yang tidak serasi",
				OptionC:  "Pemilihan huruf yang sesuai ukuran dan jenisnya",
				OptionD:  "Pemilihan ilustrasi",
				Answer:   "Tata warna dan tata letak yang tidak serasi",
			},
			{
				QuizID:   1,
				Question: "Bagian penting yang menunjukkan alur logika dari paparan yang mengalir dengan runtut, kecuali ...",
				OptionA:  "Ringkasan",
				OptionB:  "Latar belakang",
				OptionC:  "Paparan utama",
				OptionD:  "Isi",
				Answer:   "Isi",
			},
			{
				QuizID:   1,
				Question: "Keterampilan yang bersifat fundamental yang terkait dengan kemampuan mengelola diri sendiri, orang lain, informasi dan tugas adalah pengertian dari ...",
				OptionA:  "Keterampilan komputer",
				OptionB:  "Keterampilan metakognitif",
				OptionC:  "Keterampilan generik",
				OptionD:  "Keterampilan non generik",
				Answer:   "Keterampilan generik",
			},
			{
				QuizID:   1,
				Question: "Keterampilan berpikir, keterampilan pemecahan masalah, keterampilan kepemimpinan, keterampilan manajemen dan keterampilan kerja sama merupakan indikator dari keterampilan ...",
				OptionA:  "Keterampilan komputer",
				OptionB:  "Keterampilan generik",
				OptionC:  "Keterampilan metakognitif",
				OptionD:  "Keterampilan non generik",
				Answer:   "Keterampilan generik",
			},
			{
				QuizID:   1,
				Question: "Kemampuan untuk mengaitkan pesan penting dengan pengetahuan sebelumnya, menarik kesimpulan dan memantau serta menilai kinerja pribadi disebut dengan keterampilan ...",
				OptionA:  "Keterampilan komputer",
				OptionB:  "Keterampilan generik",
				OptionC:  "Keterampilan non generik",
				OptionD:  "Keterampilan metakognitif",
				Answer:   "Keterampilan metakognitif",
			},
		},
	}, {
		ID:          2,
		Name:        "BAB 2 Berpikir Komputasional ",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652833/iquest/Rectangle-1_yfrcj3.png",
		Description: "Mempelajari tentang berpikir komputasional dan penerapannya dalam pemecahan masalah.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   2,
				Question: "Berpikir komputasi memiliki empat pondasi sebagai berikut, kecuali…",
				OptionA:  "Abstraksi",
				OptionB:  "Pola",
				OptionC:  "Kritis",
				OptionD:  "Dekomposisi",
				OptionE:  "Algoritma",
				Answer:   "Kritis",
			},
			{
				QuizID:   2,
				Question: "Berpikir komputasional merupakan suatu kemampuan untuk…",
				OptionA:  "Merancang perangkat keras komputer",
				OptionB:  "Menggunakan perangkat lunak komputer",
				OptionC:  "Memecahkan masalah secara logis dan efisien",
				OptionD:  "Mengoperasikan komputer dengan cepat",
				OptionE:  "Mengembangkan jaringan komputer",
				Answer:   "Memecahkan masalah secara logis dan efisien",
			},
			{
				QuizID:   2,
				Question: "Seorang siswa diberikan tugas untuk memecahkan masalah menggunakan berpikir komputasional. Langkah pertama yang sebaiknya dilakukan adalah…",
				OptionA:  "Menulis kode program menggunakan bahasa pemrograman",
				OptionB:  "Mengidentifikasi masalah yang harus dipecahkan",
				OptionC:  "Membaca buku teks tentang algoritma",
				OptionD:  "Mencari solusi yang telah dibuat oleh orang lain di internet",
				OptionE:  "Membahas masalah dengan teman sekelas",
				Answer:   "Mengidentifikasi masalah yang harus dipecahkan",
			},
			{
				QuizID:   2,
				Question: "Ada 4 fondasi dalam berpikir komputasional sebagai berikut, kecuali ....",
				OptionA:  "Kritis",
				OptionB:  "Abstraksi",
				OptionC:  "Algoritma",
				OptionD:  "Dekomposisi",
				OptionE:  "Pola",
				Answer:   "Kritis",
			},
			{
				QuizID:   2,
				Question: "Proses mengurutkan sebuah list dengan cara menyisipkan elemen satu per satu sesuai urutan besar kecilnya disebut .....",
				OptionA:  "Bubble sort",
				OptionB:  "Insertion sort",
				OptionC:  "Quick sort",
				OptionD:  "Merge sort",
				OptionE:  "Selection sort",
				Answer:   "Insertion sort",
			},
			{
				QuizID:   2,
				Question: "Perhatikan ilustrasi berikut! Dalam sebuah bus yang sesak, orang yang masuk terakhir harus keluar dulu agar seseorang dapat yang pertama datang dan terpojok di ujung akan bisa keluar. Berdasarkan berpikir komputasi, proses ini disebut .....",
				OptionA:  "Sorting",
				OptionB:  "Searching",
				OptionC:  "Stack",
				OptionD:  "Push",
				OptionE:  "Pop",
				Answer:   "Stack",
			},
			{
				QuizID:   2,
				Question: "Apa yang dimaksud dengan deduktif?",
				OptionA:  "Pernyataan yang bernilai benar",
				OptionB:  "Berdasarkan fakta-fakta yang bersifat umum",
				OptionC:  "Pengukuran yang bertujuan untuk menarik kesimpulan",
				OptionD:  "Yang menggambarkan keadaan benar",
				Answer:   "Pengukuran yang bertujuan untuk menarik kesimpulan",
			},
			{
				QuizID:   2,
				Question: "Kata penghubung \"atau\" ditulis dengan ...",
				OptionA:  "π∧",
				OptionB:  "\"v\"",
				OptionC:  "\"@\"",
				OptionD:  "( _ )",
				Answer:   "\"v\"",
			},
			{
				QuizID:   2,
				Question: "Bilangan biner sering disebut juga dengan ...",
				OptionA:  "Proposisi",
				OptionB:  "Binary digit",
				OptionC:  "Implikasi",
				OptionD:  "Konjungsi",
				Answer:   "Binary digit",
			},
			{
				QuizID:   2,
				Question: "Apa yang dimaksud dengan proposisi ...",
				OptionA:  "Penukaran yang bertujuan untuk menarik kesimpulan",
				OptionB:  "Suatu pernyataan yang bernilai benar",
				OptionC:  "Pernyataan dalam bentuk sebuah kalimat",
				OptionD:  "Pernyataan yang menggambarkan benar atau salah",
				Answer:   "Pernyataan dalam bentuk sebuah kalimat",
			},
			{
				QuizID:   2,
				Question: "Yang dimaksud dengan implikasi adalah ...",
				OptionA:  "Ismah tidak kasih uang jajan kepada adiknya",
				OptionB:  "Ismah tidak lulus ujian",
				OptionC:  "Ismah memberikan uang jajan kepada adik-adiknya",
				OptionD:  "Ismah lulus ujian",
				Answer:   "Ismah memberikan uang jajan kepada adik-adiknya",
			},
			{
				QuizID:   2,
				Question: "Kalimat yang berkaitan dengan operator logika adalah ...",
				OptionA:  "Hari ini pemilu KPD daerah",
				OptionB:  "Peserta didik bubarkan dari sekolah",
				OptionC:  "Hari ini pemilu KPI Daerah dan peserta didik dibubarkan",
				OptionD:  "Hari ini pemilu KPI Daerah atau peserta didik dibubarkan",
				Answer:   "Hari ini pemilu KPI Daerah atau peserta didik dibubarkan",
			},
			{
				QuizID:   2,
				Question: "Apa yang dimaksud dengan pemecahan masalah?",
				OptionA:  "Hal ini karena masalah yang mereka hadapi bukanlah masalah yang dihadapi siswa sebelumnya",
				OptionB:  "Ada empat tahap pemecahan masalah yaitu (1) memahami masalah, (2) merencanakan solusi, (3) melaksanakan rencana, (4) memeriksa kembali",
				OptionC:  "Pemecahan masalah didefinisikan sebagai proses kognitif tingkat tinggi yang membutuhkan modulasi dan kontrol daripada rutinitas atau keterampilan dasar",
				OptionD:  "Pemecahan masalah tertentu melalui proses yang direncanakan yang mungkin tidak dapat dicapai dengan segera",
				Answer:   "Pemecahan masalah tertentu melalui proses yang direncanakan yang mungkin tidak dapat dicapai dengan segera",
			},
			{
				QuizID:   2,
				Question: "Yang dimaksud dengan negasi adalah ...",
				OptionA:  "Ekor monyet dihidung",
				OptionB:  "Pohon pisang akar di atas buah di bawah",
				OptionC:  "Kambing bisa berenang",
				OptionD:  "Nyamuk bisa terbang",
				Answer:   "Nyamuk bisa terbang",
			},
			{
				QuizID:   2,
				Question: "Manakah yang termasuk logika inferensi ...",
				OptionA:  "Hujan jatuh karena adanya awan hitam yang tebal",
				OptionB:  "Sampah menumpuk akibat terbawa arus banjir",
				OptionC:  "Rumah tua terlihat banyak daun berserakan dan di sekitar dinding terlihat banyak ditumbuhi lumut begitu juga debu tebal memenuhi kaca",
				OptionD:  "Kucing dan anjing selalu bertengkar jika satu sama lain bertemu",
				Answer:   "Rumah tua terlihat banyak daun berserakan dan di sekitar dinding terlihat banyak ditumbuhi lumut begitu juga debu tebal memenuhi kaca",
			},
			{
				QuizID:   2,
				Question: "Yang dimaksud dengan kata negasi lingkaran adalah ...",
				OptionA:  "Ikan bisa hidup di air",
				OptionB:  "Ikan hidup di darat",
				OptionC:  "Monyet pandai memanjat pohon",
				OptionD:  "Monyet pandai menanam pohon",
				Answer:   "Ikan bisa hidup di air",
			},
			{
				QuizID:   2,
				Question: "Yang dimaksud dengan kata induktif adalah ...",
				OptionA:  "Kesederhanaan jelas segala hal dengan bahasa ringan dan tidak bantuan dari pihak lain",
				OptionB:  "Kebensi sebisa mungkin pengejelasan yang sesuai dengan apa yang diyakini para ahli tentang dunia",
				OptionC:  "Pendiktabilitas sebisa mungkin pengjelasan yg paling banyak penghasilan predisi yg dapat di sukai atau dilayakan",
				OptionD:  "Komprehensi sebisa mungkin pilih pengjelasan yg paling lengkap dan meninggalkan sedikit sekali ketidakjelasan",
				Answer:   "Pendiktabilitas sebisa mungkin pengjelasan yg paling banyak penghasilan predisi yg dapat di sukai atau dilayakan",
			},
			{
				QuizID:   2,
				Question: "Contoh kalimat negasi adalah ...",
				OptionA:  "Monyet pandai menanam pohon",
				OptionB:  "Monyet pandai panjat pohon",
				OptionC:  "Ikan bisa hidup di darat",
				OptionD:  "Monyet bisa hidup di air",
				Answer:   "Monyet pandai panjat pohon",
			},
			{
				QuizID:   2,
				Question: "Kata hubung konjungsi adalah ...",
				OptionA:  "Dan",
				OptionB:  "Di",
				OptionC:  "Dengan",
				OptionD:  "Yang",
				Answer:   "Dan",
			},
			{
				QuizID:   2,
				Question: "Partisipasi masyarakat dalam keluarga berencana meningkat ... mereka menyadari manfaat keluarga kecil.",
				OptionA:  "Setelah",
				OptionB:  "Sehingga",
				OptionC:  "Namun",
				OptionD:  "Dengan",
				Answer:   "Setelah",
			},
		},
	}, {
		ID:          3,
		Name:        "BAB 3 Teknologi informasi dan komunikasi",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652834/iquest/Rectangle-2_v3dbzb.png",
		Description: "Mempelajari tentang teknologi informasi dan komunikasi yang diperlukan dalam dunia digital.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   3,
				Question: "Contoh Input Device ...",
				OptionA:  "Modem",
				OptionB:  "Speaker",
				OptionC:  "Keyboard",
				OptionD:  "Monitor",
				Answer:   "Keyboard",
			},
			{
				QuizID:   3,
				Question: "Contoh dari output device ...",
				OptionA:  "Speaker",
				OptionB:  "Mouse",
				OptionC:  "CPU",
				OptionD:  "Memory",
				Answer:   "Speaker",
			},
			{
				QuizID:   3,
				Question: "Yang termasuk kedalam peripheral device adalah ...",
				OptionA:  "VGA",
				OptionB:  "RAM",
				OptionC:  "Modem",
				OptionD:  "ROM",
				Answer:   "Modem",
			},
			{
				QuizID:   3,
				Question: "Aplikasi perkantoran yang digunakan untuk mengolah Teks adalah ...",
				OptionA:  "Ms. Power Point",
				OptionB:  "Ms. Word",
				OptionC:  "Ms. Excel",
				OptionD:  "Ms. Office",
				Answer:   "Ms. Word",
			},
			{
				QuizID:   3,
				Question: "Komponen UTAMA dari sebuah presentasi adalah ...",
				OptionA:  "Presenter, Audiens, Sounds",
				OptionB:  "Presenter, Audiens, Media",
				OptionC:  "Audiens, Media, Sound",
				OptionD:  "Media, Presenter, Sound",
				Answer:   "Presenter, Audiens, Media",
			},
			{
				QuizID:   3,
				Question: "Untuk membuka lembar kerja baru dalam Ms. Word, dapat menggunakan shortcut?",
				OptionA:  "Ctrl + O",
				OptionB:  "Ctrl + X",
				OptionC:  "Ctrl + N",
				OptionD:  "Ctrl + Y",
				Answer:   "Ctrl + N",
			},
			{
				QuizID:   3,
				Question: "Shortcut untuk menempelkan hasil dari Copy/Cut adalah ...",
				OptionA:  "Ctrl + P",
				OptionB:  "Ctrl + O",
				OptionC:  "Ctrl + X",
				OptionD:  "Ctrl + V",
				Answer:   "Ctrl + V",
			},
			{
				QuizID:   3,
				Question: "Lembar kerja dalam aplikasi pengolah angka sering disebut ...",
				OptionA:  "Dokumen",
				OptionB:  "Spreadsheet",
				OptionC:  "Slide",
				OptionD:  "Layer",
				Answer:   "Spreadsheet",
			},
			{
				QuizID:   3,
				Question: "Memory yang menyimpan data bersifat sementara disebut ...",
				OptionA:  "RAM",
				OptionB:  "ROM",
				OptionC:  "Flasdisk",
				OptionD:  "Harddisk",
				Answer:   "RAM",
			},
			{
				QuizID:   3,
				Question: "Input device yang menangkap data berupa audio adalah ...",
				OptionA:  "Speaker",
				OptionB:  "Plotter",
				OptionC:  "Microphone",
				OptionD:  "Scanner",
				Answer:   "Microphone",
			},
			{
				QuizID:   3,
				Question: "Sistem bilangan yang mempunyai 10 digit angka adalah ...",
				OptionA:  "Sistem bilangan desimal",
				OptionB:  "Sistem bilangan oktal",
				OptionC:  "Sistem bilangan biner",
				OptionD:  "Sistem bilangan pecahan",
				Answer:   "Sistem bilangan desimal",
			},
			{
				QuizID:   3,
				Question: "Sistem bilangan yang berbasis 8 adalah ...",
				OptionA:  "Sistem bilangan desimal",
				OptionB:  "Sistem bilangan oktal",
				OptionC:  "Sistem bilangan biner",
				OptionD:  "Sistem bilangan heksadesimal",
				Answer:   "Sistem bilangan oktal",
			},
			{
				QuizID:   3,
				Question: "Bilangan desimal 178 bila dikonversikan ke bilangan biner adalah ...",
				OptionA:  "10010010",
				OptionB:  "10110011",
				OptionC:  "11110010",
				OptionD:  "10110010",
				Answer:   "10110010",
			},
			{
				QuizID:   3,
				Question: "Bilangan desimal 152 bila dikonversikan ke bilangan oktal adalah ...",
				OptionA:  "230",
				OptionB:  "231",
				OptionC:  "232",
				OptionD:  "233",
				Answer:   "230",
			},
			{
				QuizID:   3,
				Question: "Bilangan desimal 4821 bila dikonversikan ke bilangan heksadesimal adalah ...",
				OptionA:  "13D6",
				OptionB:  "11D5",
				OptionC:  "12D5",
				OptionD:  "11D6",
				Answer:   "12D5",
			},
			{

				QuizID:   3,
				Question: "Bilangan biner 11100 bila dikonversikan ke bilangan desimal adalah ...",
				OptionA:  "25",
				OptionB:  "26",
				OptionC:  "27",
				OptionD:  "28",
				Answer:   "28",
			},
			{
				QuizID:   3,
				Question: "Bilangan biner 101011 bila dikonversikan ke bilangan oktal adalah ...",
				OptionA:  "50",
				OptionB:  "51",
				OptionC:  "52",
				OptionD:  "53",
				Answer:   "50",
			},
			{
				QuizID:   3,
				Question: "Bilangan biner 11000110 bila dikonversikan ke bilangan heksadesimal adalah ...",
				OptionA:  "D6",
				OptionB:  "C6",
				OptionC:  "A6",
				OptionD:  "C7",
				Answer:   "C6",
			},
			{
				QuizID:   3,
				Question: "Bilangan oktal 1541 bila dikonversikan ke bilangan desimal adalah ...",
				OptionA:  "865",
				OptionB:  "866",
				OptionC:  "867",
				OptionD:  "868",
				Answer:   "865",
			},
			{
				QuizID:   3,
				Question: "Bilangan oktal 96 bila dikonversikan ke bilangan biner adalah ...",
				OptionA:  "1001111",
				OptionB:  "1001010",
				OptionC:  "1001110",
				OptionD:  "1011110",
				Answer:   "1001110",
			},
		},
	}, {
		ID:          4,
		Name:        "BAB 4 Sistem Komputer",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652836/iquest/Rectangle-3_f5gf5a.png",
		Description: "Mempelajari tentang sistem komputer, komponen-komponennya, dan cara kerjanya.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   4,
				Question: "Komponen yang bersifat fisik, dapat dilihat dan disentuh disebut dengan ...",
				OptionA:  "Hardware",
				OptionB:  "Software",
				OptionC:  "Brainware",
				OptionD:  "Output",
				Answer:   "Hardware",
			},
			{
				QuizID:   4,
				Question: "Perangkat keras masukan disebut juga dengan istilah ...",
				OptionA:  "Outout Devices",
				OptionB:  "Inut Devices",
				OptionC:  "Process Devices",
				OptionD:  "Storage Devices",
				Answer:   "Inut Devices",
			},
			{
				QuizID:   4,
				Question: "Alat yang digunakan untuk mengkonversi atau mengubah gambar/dokumen manual menjadi gambar/dokumen digital adalah ...",
				OptionA:  "Printer",
				OptionB:  "Speaker",
				OptionC:  "Monitor",
				OptionD:  "Scanner",
				Answer:   "Scanner",
			},
			{
				QuizID:   4,
				Question: "Komponen dari CPU yang bertugas melakukan perhitungan aritmatika dan pembandingan adalah ...",
				OptionA:  "Control Unit",
				OptionB:  "ALU",
				OptionC:  "Memory Unit",
				OptionD:  "Processor Unit",
				Answer:   "ALU",
			},
			{
				QuizID:   4,
				Question: "Bilangan biner adalah bilangan yang berbasis ...",
				OptionA:  "Bilangan yang berbasis 2 yaitu 1 dan 2",
				OptionB:  "Bilangan yang berbasis 2 yaitu 90 dan 1",
				OptionC:  "Bilangan yang berbasis 10 yaitu 0 – 9",
				OptionD:  "Bilangan yang berbasis 8 yaitu 0 - 7",
				Answer:   "Bilangan yang berbasis 2 yaitu 90 dan 1",
			},
			{
				QuizID:   4,
				Question: "Bilangan oktal adalah bilangan yang berbasis ...",
				OptionA:  "Bilangan yang berbasis 8 yaitu 0 dan 8",
				OptionB:  "Bilangan yang berbasis 2 yaitu 0 dan 1",
				OptionC:  "Bilangan yang berbasis 8 yaitu 0 – 7",
				OptionD:  "Bilangan yang berbasis 10 yaitu 0 - 9",
				Answer:   "Bilangan yang berbasis 8 yaitu 0 – 7",
			},
			{
				QuizID:   4,
				Question: "Alat yang digunakan untuk dapat mengembalikan proses encoding sehingga dapat melihat atau menerima informasi aslinya disebut ...",
				OptionA:  "Dekoder",
				OptionB:  "Multiplexer",
				OptionC:  "Flip-flop",
				OptionD:  "Register",
				Answer:   "Dekoder",
			},
			{
				QuizID:   4,
				Question: "Konversi bilangan biner 1101 0100 ke heksadesimal adalah ...",
				OptionA:  "B 3",
				OptionB:  "D 4",
				OptionC:  "C 4",
				OptionD:  "D 2",
				Answer:   "D 4",
			},
			{
				QuizID:   4,
				Question: "Konsep perencanaan dan struktur pengoperasian dasar dari suatu sistem komputer disebut ...",
				OptionA:  "Arsitektur Komputer",
				OptionB:  "Sistem Komputer",
				OptionC:  "Aplikasi Komputer",
				OptionD:  "Instalasi Komputer",
				Answer:   "Arsitektur Komputer",
			},
			{
				QuizID:   4,
				Question: "Bagian yang terhubung dengan komponen pelaksanaan dan inter koneksi antar komponen penyusun sistem komputer dalam melaksanakan aspek arsitekturnya disebut ...",
				OptionA:  "Aplikasi komputer",
				OptionB:  "Organisasi Komputer",
				OptionC:  "Dasar Komputer",
				OptionD:  "Sistem Komputer",
				Answer:   "Organisasi Komputer",
			},
			{
				QuizID:   4,
				Question: "Berikut ini manakah yang bukan merupakan program Microsoft Office yaitu ...",
				OptionA:  "Microsoft Word",
				OptionB:  "Microsoft Excel",
				OptionC:  "Microsoft Access",
				OptionD:  "CorelDraw",
				Answer:   "CorelDraw",
			},
			{
				QuizID:   4,
				Question: "Untuk menggulung layar ke atas atau ke bawah digunakan ...",
				OptionA:  "Scrollbar",
				OptionB:  "Border",
				OptionC:  "Title Bar",
				OptionD:  "Toolbar",
				Answer:   "Scrollbar",
			},
			{
				QuizID:   4,
				Question: "Syarat penulisan formula pada Microsoft Excel harus menggunakan tanda ...",
				OptionA:  "=",
				OptionB:  "#",
				OptionC:  ":",
				OptionD:  "@",
				Answer:   "=",
			},
			{
				QuizID:   4,
				Question: "User nama lain dari ...",
				OptionA:  "Penjual",
				OptionB:  "Agent",
				OptionC:  "Pengguna",
				OptionD:  "Pedagang",
				OptionE:  "Penyalur",
				Answer:   "Pengguna",
			},
			{
				QuizID:   4,
				Question: "Bahasa yang digunakan pada bahasa pemrograman tingkat rendah adalah ...",
				OptionA:  "Mesin",
				OptionB:  "Basic",
				OptionC:  "Assembler",
				OptionD:  "Pascal",
				OptionE:  "Delphi",
				Answer:   "Mesin",
			},
			{
				QuizID:   4,
				Question: "Sebuah komponen fisik pada komputer yang digunakan oleh sistem untuk menjalankan perintah yang telah diprogram disebut ...",
				OptionA:  "VGA",
				OptionB:  "Software",
				OptionC:  "Aplikasi",
				OptionD:  "Hardware",
				OptionE:  "RAM",
				Answer:   "Hardware",
			},
			{
				QuizID:   4,
				Question: "Gejala kerusakan yang biasanya terjadi pada motherboard adalah ...",
				OptionA:  "Optical drive tidak terdeteksi oleh sistem operasi",
				OptionB:  "CPU mengeluarkan suara beep beberapa kali dan tidak ada tampilan layar monitor, padahal monitor tidak bermasalah",
				OptionC:  "Tidak bisa membaca atau menulis kepingan CD/DVD",
				OptionD:  "Setelah komputer hidup, tidak ada tampilan monitor, lampu indikator monitor berkedip, kipas PSU dan kipas prosesor berputar, tetapi tidak ada suara beep di speaker",
				OptionE:  "Mekanisme keluar-masuk tidak bekerja",
				Answer:   "Setelah komputer hidup, tidak ada tampilan monitor, lampu indikator monitor berkedip, kipas PSU dan kipas prosesor berputar, tetapi tidak ada suara beep di speaker",
			},
			{
				QuizID:   4,
				Question: "Ada berapa macam perangkat keras komputer?",
				OptionA:  "14",
				OptionB:  "12",
				OptionC:  "10",
				OptionD:  "8",
				OptionE:  "6",
				Answer:   "14",
			},
			{
				QuizID:   4,
				Question: "Membuat program-program yang diperlukan pada sistem komputerisasi yang akan dirancang merupakan tugas dari ...",
				OptionA:  "Pengguna",
				OptionB:  "Programmer",
				OptionC:  "Operator",
				OptionD:  "Administrator",
				OptionE:  "Gamers",
				Answer:   "Programmer",
			},
			{
				QuizID:   4,
				Question: "Fungsi perangkat proses adalah ...",
				OptionA:  "Menghapus file atau data-data yang dikirimkan oleh pengguna",
				OptionB:  "Menampilkan hasil yang telah diolah oleh komputer dan selanjutnya diberikan pada pengguna",
				OptionC:  "Menyalin semua data yang dimiliki pengguna",
				OptionD:  "Memproses input yang diberikan oleh pengguna",
				OptionE:  "Memasukkan input dari pengguna yang akan diproses oleh computer",
				Answer:   "Memproses input yang diberikan oleh pengguna",
			},
		},
	}, {
		ID:          5,
		Name:        "BAB 5 Jaringan Komputer dan Internet",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652832/iquest/Rectangle-4_hcuhke.png",
		Description: "Mempelajari tentang jaringan komputer dan internet, termasuk cara kerjanya dan jenis-jenis jaringannya.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   5,
				Question: "Sistem yang menghubungkan dua atau lebih komputer untuk berbagi data yaitu ...",
				OptionA:  "Jaringan komputer",
				OptionB:  "Jaringan internet",
				OptionC:  "WIFI",
				OptionD:  "Bluetooth",
				Answer:   "Jaringan komputer",
			},
			{
				QuizID:   5,
				Question: "Komputer yang digunakan untuk menyimpan database dan mengelola segala aktivitas yang terjadi dalam jaringan komputer ...",
				OptionA:  "Komputer Client",
				OptionB:  "Komputer Pengguna",
				OptionC:  "Modem",
				OptionD:  "Komputer Server",
				Answer:   "Komputer Server",
			},
			{
				QuizID:   5,
				Question: "Pemberi IP Address ...",
				OptionA:  "Modem",
				OptionB:  "NIC",
				OptionC:  "Router",
				OptionD:  "Komputer Server",
				Answer:   "Router",
			},
			{
				QuizID:   5,
				Question: "Memperkuat sinyal ...",
				OptionA:  "Modem",
				OptionB:  "Hub",
				OptionC:  "Repeater",
				OptionD:  "Bridge",
				Answer:   "Repeater",
			},
			{
				QuizID:   5,
				Question: "Kabel yang terbuat dari kaca ...",
				OptionA:  "Coaxial",
				OptionB:  "UTP",
				OptionC:  "Twisted pair",
				OptionD:  "Fiber Optic",
				Answer:   "Fiber Optic",
			},
			{
				QuizID:   5,
				Question: "192.268.0.21 adalah penulisan dari ...",
				OptionA:  "IP Address",
				OptionB:  "IP Imei",
				OptionC:  "Modem",
				OptionD:  "Jaringan",
				Answer:   "IP Address",
			},
			{
				QuizID:   5,
				Question: "HTTPS kepanjangan dari ...",
				OptionA:  "Hypertext Transfer Protocol",
				OptionB:  "Hypertext Transfer Proteksi",
				OptionC:  "Hub Transfer Protocol",
				OptionD:  "Hub Transfer Proteksi",
				Answer:   "Hypertext Transfer Protocol",
			},
			{
				QuizID:   5,
				Question: "Jaringan komputer yang mencakup wilayah yang cenderung kecil ...",
				OptionA:  "LAN",
				OptionB:  "WAN",
				OptionC:  "PAN",
				OptionD:  "MAN",
				Answer:   "PAN",
			},
			{
				QuizID:   5,
				Question: "VPN kepanjangan dari ...",
				OptionA:  "Virtual Protocol Network",
				OptionB:  "Vase Protocol Network",
				OptionC:  "Virtual Private Network",
				OptionD:  "Vase Private Network",
				Answer:   "Virtual Private Network",
			},
			{
				QuizID:   5,
				Question: "Jenis jaringan komputer yang menggunakan kabel sebagai media transmisi atau penghantarnya ...",
				OptionA:  "Wire network",
				OptionB:  "Wireless",
				OptionC:  "Wifi",
				OptionD:  "Hotspot",
				Answer:   "Wire network",
			},
			{
				QuizID:   5,
				Question: "Keuntungan menggunakan jaringan, kecuali ...",
				OptionA:  "Sharing data",
				OptionB:  "Menghemat uang",
				OptionC:  "Menghemat perbaikan jaringan",
				OptionD:  "Rehabilitas tinggi",
				Answer:   "Rehabilitas tinggi",
			},
			{
				QuizID:   5,
				Question: "Kelebihan jaringan internet ...",
				OptionA:  "Tempat berkembangnya aktivitas illegal",
				OptionB:  "Pertukaran data",
				OptionC:  "Masalah kesehatan",
				OptionD:  "Kekerasan",
				Answer:   "Pertukaran data",
			},
			{
				QuizID:   5,
				Question: "Jenis dari koneksi wireless pertama adalah ...",
				OptionA:  "Wifi",
				OptionB:  "Akses Satelit",
				OptionC:  "Modem",
				OptionD:  "GPRS",
				Answer:   "GPRS",
			},
			{
				QuizID:   5,
				Question: "Jaringan yang memiliki nilai kecepatan 100Mbps-1Gbps ...",
				OptionA:  "5G",
				OptionB:  "4G",
				OptionC:  "3G",
				OptionD:  "3.5G",
				Answer:   "4G",
			},
			{
				QuizID:   5,
				Question: "Mengotentikasi identitas situs web untuk meyakinkan pengunjung bahwa web yang diakses bukan web palsu ...",
				OptionA:  "SSL",
				OptionB:  "HTTP",
				OptionC:  "SSE",
				OptionD:  "HTTPS",
				Answer:   "HTTPS",
			},
			{
				QuizID:   5,
				Question: "Sistem yang menghubungkan dua atau lebih komputer untuk berbagi data yaitu ...",
				OptionA:  "Jaringan komputer",
				OptionB:  "Jaringan internet",
				OptionC:  "WIFI",
				OptionD:  "Bluetooth",
				Answer:   "Jaringan komputer",
			},
			{
				QuizID:   5,
				Question: "Komputer yang digunakan untuk menyimpan database dan mengelola segala aktivitas yang terjadi dalam jaringan komputer ...",
				OptionA:  "Komputer Client",
				OptionB:  "Komputer Pengguna",
				OptionC:  "Modem",
				OptionD:  "Komputer Server",
				Answer:   "Komputer Server",
			},
			{
				QuizID:   5,
				Question: "Pemberi IP Address ...",
				OptionA:  "Modem",
				OptionB:  "NIC",
				OptionC:  "Router",
				OptionD:  "Komputer Server",
				Answer:   "Router",
			},
			{
				QuizID:   5,
				Question: "Memperkuat sinyal ...",
				OptionA:  "Modem",
				OptionB:  "Hub",
				OptionC:  "Repeater",
				OptionD:  "Bridge",
				Answer:   "Repeater",
			},
			{
				QuizID:   5,
				Question: "Kabel yang terbuat dari kaca ...",
				OptionA:  "Coaxial",
				OptionB:  "UTP",
				OptionC:  "Twisted pair",
				OptionD:  "Fiber Optic",
				Answer:   "Fiber Optic",
			},
		},
	}, {
		ID:          6,
		Name:        "BAB 6 Analisis Data",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652834/iquest/Rectangle-5_ktyjon.png",
		Description: "Mempelajari tentang analisis data, teknik-teknik analisis, dan penerapannya dalam berbagai bidang.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   6,
				Question: "Sekumpulan keterangan atau fakta mentah berupa simbol, angka, angka-angka atau citra yang didaparkan melalui proses pengamatan atau pencarian ke sumber-sumber tertentu, adalah pengertian dari ...",
				OptionA:  "Pesan",
				OptionB:  "Informasi",
				OptionC:  "Data",
				OptionD:  "Media",
				Answer:   "Data",
			},
			{
				QuizID:   6,
				Question: "Upaya atau cara untuk mengolah data menjadi informasi sehingga karakteristik data tersebut bisa dipahami dan bermanfaat untuk solusi permasalahan, terutama masalah yang berkaitan dengan penelitian adalah pengertian dari ...",
				OptionA:  "Analisis Informasi",
				OptionB:  "Data",
				OptionC:  "Analisis Media",
				OptionD:  "Analisis Data",
				Answer:   "Analisis Data",
			},
			{
				QuizID:   6,
				Question: "Perhatikan tahap-tahap di bawah ini!\n1. Tahap pengumpulan data\n2. Tahap pengujian\n3. Tahap tabulasi\n4. Tahap koding\n5. Tahap mendeskripsikan data\n6. Tahap pengujian hipotesis\nLangkah dan prosedur analisis data dibawah ini yang benar adalah ...",
				OptionA:  "1,4,3,2,5,6",
				OptionB:  "1,5,3,6,4,2",
				OptionC:  "2,4,3,1,5,6",
				OptionD:  "1,4,5,2,3,6",
				Answer:   "1,4,3,2,5,6",
			},
			{
				QuizID:   6,
				Question: "Melakukan kegiatan mencatat ataupun entri data kedalam tabel-tabel induk dalam penelitian. Tahap ini dinamakan ..",
				OptionA:  "Tahap koding",
				OptionB:  "Tahap tabulasi",
				OptionC:  "Tahap pengujian",
				OptionD:  "Tahap penelitian",
				Answer:   "Tahap tabulasi",
			},
			{
				QuizID:   6,
				Question: "Teknik analisis data dalam penelitian ada dua jenis yaitu ...",
				OptionA:  "Kualitatif dan Diskriminatif",
				OptionB:  "Kuantitatif dan Kondisional",
				OptionC:  "Kualitatif dan Kuantitatif",
				OptionD:  "Kualitatif dan Deskriptif",
				Answer:   "Kualitatif dan Kuantitatif",
			},
			{
				QuizID:   6,
				Question: "Analisis yang menggunakan model-model seperti model matematika misalnya fungsi multivariat model statistik, dan ekonometrik. Hasil analisis disajikan dalam bentuk angka-angka yang kemudian dijelaskan dan diinterpretasikan dalam suatu uraian. Termasuk pengertian data ...",
				OptionA:  "Kualitatif",
				OptionB:  "Kuantitatif",
				OptionC:  "Deskriptif",
				OptionD:  "Diskiminatif",
				Answer:   "Kuantitatif",
			},
			{
				QuizID:   6,
				Question: "Proses secara sistematis mencari dan mengolah berbagai data yang bersumber dari wawancara, pengamatan. lapangam dam kajian dokumen (pustaka) untuk menghasilkan suatu laporan temuan penelitian. Termasuk pengertian data ...",
				OptionA:  "Kualitatif",
				OptionB:  "Kuantitatif",
				OptionC:  "Deskriptif",
				OptionD:  "Diskriminatif",
				Answer:   "Kualitatif",
			},
			{
				QuizID:   6,
				Question: "Teknik analisis yang digunakan dalam menganalisis data dengan membuat gambaran data-data yang terkumpul tanpa membuat generalisasi dari hasil penelitian tersebut adalah analisis data bersifat ...",
				OptionA:  "Deskriptif",
				OptionB:  "Kuantitatif",
				OptionC:  "Kualitatif",
				OptionD:  "Diskriminatif",
				Answer:   "Deskriptif",
			},
			{
				QuizID:   6,
				Question: "Beberapa yang termasuk di dalam teknik analisis data secara deskriptif misalnya menyajikan data ke dalam bentuk dibawah ini, kecuali ...",
				OptionA:  "Tabel",
				OptionB:  "Grafik",
				OptionC:  "Presentasi",
				OptionD:  "Flowchart",
				Answer:   "Flowchart",
			},
			{
				QuizID:   6,
				Question: "Yang tidak termasuk beberapa keuntungan melakukan analisis data bagi sebuah penelitian adalah ...",
				OptionA:  "Proses identifikasi lebih reliable",
				OptionB:  "Mendapatkan hasil pengukuran yang lebih jelas",
				OptionC:  "Data dapat dimanipulasi untuk keuntungan materi",
				OptionD:  "Memungkinkan untuk melakukan identifikasi pada hal-hal yang penting",
				Answer:   "Data dapat dimanipulasi untuk keuntungan materi",
			},
			{
				QuizID:   6,
				Question: "Analisis data adalah proses yang merinci usaha formal untuk menemukan tema dan merumuskan hipotesis (ide) seperti yang disarankan oleh data dan sebagai usaha untuk memberikan bantuan pada tema dan hipotesis. Itu dikemukakan oleh ...",
				OptionA:  "Patton (1980)",
				OptionB:  "Lexy J. Moleong (2000)",
				OptionC:  "Jhon Dalton (1975)",
				OptionD:  "Bogdan dan Taylor (1975)",
				Answer:   "Bogdan dan Taylor (1975)",
			},
			{
				QuizID:   6,
				Question: "Merupakan proses identifikasi dan proses klasifikasi dari tiap-tiap pernyataan yang terdapat pada instrumen pengumpulan data berdasarkan variabel yang sedang diteliti. Tahapan in dinamakan ...",
				OptionA:  "Tabulasi",
				OptionB:  "Koding",
				OptionC:  "Pengujian",
				OptionD:  "Deskripsi",
				Answer:   "Koding",
			},
			{
				QuizID:   6,
				Question: "Menyajikan dalam bentuk tabel frekuensi ataupun diagram dalam berbagai macam ukuran tendensi sentral maupun ukuran dispersi. Tahapan ini dinamakan ...",
				OptionA:  "Tabulasi",
				OptionB:  "Koding",
				OptionC:  "Pengujian",
				OptionD:  "Deskripsi",
				Answer:   "Deskripsi",
			},
			{
				QuizID:   6,
				Question: "Tahap ini merupakan tahapan pengujian terhadap proposisi apakah ditolak atau bisa diterima dan memiliki makna atau tidak atas dasar hipotesis inilah nantinya keputusan akan dibuat. Tahapan ini dinamakan ...",
				OptionA:  "Tabulasi",
				OptionB:  "Koding",
				OptionC:  "Hipotesis",
				OptionD:  "Deskripsi",
				Answer:   "Hipotesis",
			},
			{
				QuizID:   6,
				Question: "Analisis data adalah proses mengatur data, mengorganisasikannya kedalam suatu pola, kategori dan satuan uraian dasar, dikemukakan oleh ...",
				OptionA:  "Patton (1980)",
				OptionB:  "Lexy J. Moleong (2000)",
				OptionC:  "Jhon Dalton (1975)",
				OptionD:  "Bogdan dan Taylor (1975)",
				Answer:   "Patton (1980)",
			},
			{
				QuizID:   6,
				Question: "Apa yang dimaksud dengan web scraping?",
				OptionA:  "Proses mengirim email melalui web.",
				OptionB:  "Proses mengambil data dari situs web secara otomatis.",
				OptionC:  "Proses membuat website baru.",
				OptionD:  "Proses menyimpan data ke dalam database.",
				OptionE:  "Proses mencari informasi di mesin pencari.",
				Answer:   "B. Proses mengambil data dari situs web secara otomatis.",
			},
			{
				QuizID:   6,
				Question: "Langkah pertama dalam web scraping adalah melakukan apa?",
				OptionA:  "Membuka Google Colaboratory.",
				OptionB:  "Membuka catatan baru.",
				OptionC:  "Parsing kode HTML dari situs web.",
				OptionD:  "Mengubah data menjadi tabel.",
				OptionE:  "Mengirim email.",
				Answer:   "B. Membuka catatan baru.",
			},
			{
				QuizID:   6,
				Question: "Apa yang dimaksud dengan parsing dalam konteks web scraping?",
				OptionA:  "Proses mengirim email ke situs web.",
				OptionB:  "Proses mengubah data menjadi tabel.",
				OptionC:  "Proses mengambil kode HTML dari situs web secara utuh.",
				OptionD:  "Proses mengambil data dari situs web.",
				OptionE:  "Proses membuat website baru.",
				Answer:   "C. Proses mengambil kode HTML dari situs web secara utuh.",
			},
			{
				QuizID:   6,
				Question: "Apa yang bisa diambil dari kode HTML sebuah situs web dalam web scraping?",
				OptionA:  "Nama pengguna dan kata sandi.",
				OptionB:  "Alamat situs web.",
				OptionC:  "Data posisi pekerjaan, instansi, dan gaji.",
				OptionD:  "Tanggal lahir pengguna.",
				OptionE:  "Data pribadi pengguna.",
				Answer:   "C. Data posisi pekerjaan, instansi, dan gaji.",
			},
			{
				QuizID:   6,
				Question: "Apa yang perlu dilakukan setelah mengambil kode HTML dari situs web dalam web scraping?",
				OptionA:  "Mengubahnya menjadi teks biasa.",
				OptionB:  "Menyimpannya dalam folder lokal.",
				OptionC:  "Memproses setiap elemen kode HTML untuk mendapatkan data yang penting.",
				OptionD:  "Mengirim email ke pengguna situs web.",
				OptionE:  "Mengganti kode HTML dengan kode baru.",
				Answer:   "Memproses setiap elemen kode HTML untuk mendapatkan data yang penting.",
			},
		},
	}, {
		ID:          7,
		Name:        "BAB 7 Algoritma dan Pemrograman",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652837/iquest/Rectangle-6_kzxfgb.png",
		Description: "Mempelajari tentang algoritma dan pemrograman termasuk cara menulis kode program yang efisien.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   7,
				Question: "Kumpulan instruksi terstruktur dan terbatas yang diimplementasikan dalam bentuk program komputer adalah ...",
				OptionA:  "Algoritma",
				OptionB:  "Coding",
				OptionC:  "Debugging",
				OptionD:  "Setting",
				Answer:   "Algoritma",
			},
			{
				QuizID:   7,
				Question: "Kata algoritma berasal dari ilmuwan bernama ...",
				OptionA:  "Al-Goritma",
				OptionB:  "Al-Gorism",
				OptionC:  "Al-Khawarits",
				OptionD:  "Al-Khawarizmi",
				Answer:   "Al-Khawarizmi",
			},
			{
				QuizID:   7,
				Question: "Urutan langkah-langkah yang benar sesuai dengan logika manusia disebut ...",
				OptionA:  "Logika",
				OptionB:  "Algoritma",
				OptionC:  "Operasi",
				OptionD:  "Flowchart",
				Answer:   "Algoritma",
			},
			{
				QuizID:   7,
				Question: "Berikut ini merupakan beberapa bahasa pemrograman, kecuali ...",
				OptionA:  "Pascal",
				OptionB:  "Cobol",
				OptionC:  "Prolog",
				OptionD:  "Word",
				Answer:   "Word",
			},
			{
				QuizID:   7,
				Question: "Perhatikan petikan algoritma berikut : Algoritma luas segitiga\n1. Mulai\n2. Masukkan tinggi\n3. Masukkan alas\n4. ....\n5. Tampilkan luas\n6. Selesai\nLangkah ke 4 adalah ...",
				OptionA:  "Luas = 1/2 x panjang x tinggi",
				OptionB:  "Luas = alas x tinggi",
				OptionC:  "Luas = 1/2 x alas x tinggi",
				OptionD:  "Luas = 1/4 x panjang x tinggi",
				Answer:   "Luas = 1/2 x alas x tinggi",
			},
			{
				QuizID:   7,
				Question: "Untuk memulai sebuah algoritma menggunakan simbol ...",
				OptionA:  "Terminator",
				OptionB:  "I/O",
				OptionC:  "Proses",
				OptionD:  "Decision",
				Answer:   "Terminator",
			},
			{
				QuizID:   7,
				Question: "Untuk mengolah rumus dalam sebuah algoritma menggunakan simbol ...",
				OptionA:  "Terminator",
				OptionB:  "I/O",
				OptionC:  "Persegi Panjang",
				OptionD:  "Decision",
				Answer:   "Persegi Panjang",
			},
			{
				QuizID:   7,
				Question: "Simbol jajar genjang berfungsi sebagai sarana ...",
				OptionA:  "Terminator",
				OptionB:  "I/O",
				OptionC:  "Persegi Panjang",
				OptionD:  "Decision",
				Answer:   "I/O",
			},
			{
				QuizID:   7,
				Question: "Simbol yang digunakan untuk menunjukkan sebuah kondisi keputusan adalah simbol ...",
				OptionA:  "Terminator",
				OptionB:  "I/O",
				OptionC:  "Persegi panjang",
				OptionD:  "Ketupat",
				Answer:   "Ketupat",
			},
			{
				QuizID:   7,
				Question: "Perhatikan alur algoritma berikut ini!\nMulai → Input Alas → Input Tinggi → Luas ← (alas * tinggi) / 2 → Tampil luas → Selesai\nAlgoritma di atas adalah algoritma ..",
				OptionA:  "Luas Segitiga",
				OptionB:  "Luas Persegi",
				OptionC:  "Luas Lingkaran",
				OptionD:  "Luas Jajar Genjang",
				Answer:   "Luas Segitiga",
			},
			{
				QuizID:   7,
				Question: "Serangkaian langkah atau instruksi untuk memecahkan masalah tertentu disebut ...",
				OptionA:  "Algoritma pemrograman",
				OptionB:  "Algoritma percabangan",
				OptionC:  "Algoritma deskriptif",
				OptionD:  "Algoritma komulatif",
				OptionE:  "Algoritma",
				Answer:   "Algoritma pemrograman",
			},
			{
				QuizID:   7,
				Question: "Fungsi dari algoritma adalah ...",
				OptionA:  "Untuk menentukan alur chart",
				OptionB:  "Untuk mensinkronkan data",
				OptionC:  "Untuk menentukan alur logika program",
				OptionD:  "Untuk menentukan kebenaran data",
				OptionE:  "Untuk menyajikan algoritma",
				Answer:   "Untuk menentukan alur logika program",
			},
			{
				QuizID:   7,
				Question: "Dibawah ini yang bukan penyajian algoritma programming, yaitu ...",
				OptionA:  "Flowchart",
				OptionB:  "Definition Diagram",
				OptionC:  "Pseudocode",
				OptionD:  "Algoritma deskriptif",
				OptionE:  "Algoritma komulatif",
				Answer:   "Definition Diagram",
			},
			{
				QuizID:   7,
				Question: "Cara penulisan program secara informal dengan kaidah sendiri, daripada menggunakan aturan yang ditetapkan bahasa pemrograman disebut ...",
				OptionA:  "Programming",
				OptionB:  "Flowchart",
				OptionC:  "DFD",
				OptionD:  "Deskriptif",
				OptionE:  "Pseudocode",
				Answer:   "Pseudocode",
			},
			{
				QuizID:   7,
				Question: "Diagram yang menampilkan proses dan langkah pengambilan keputusan dalam suatu program yaitu ...",
				OptionA:  "DFD",
				OptionB:  "Deskriptif",
				OptionC:  "Flowchart",
				OptionD:  "Pseudocode",
				OptionE:  "Programming",
				Answer:   "Flowchart",
			},
			{

				QuizID:   7,
				Question: "Merupakan bentukan penulisan yang menggunakan bahasa manusia sehari-hari disebut algoritma ...",
				OptionA:  "Flowchart",
				OptionB:  "Deskriptif",
				OptionC:  "Imajinatif",
				OptionD:  "Konsekuensial",
				OptionE:  "Pseudocode",
				Answer:   "Deskriptif",
			},
			{
				QuizID:   7,
				Question: "Di dalam pemrograman, algoritma bekerja dengan mengandalkan tiga aspek utama, yakni ...",
				OptionA:  "Proses → input → output",
				OptionB:  "Input → output → proses",
				OptionC:  "Input → proses → output",
				OptionD:  "Output → input",
				OptionE:  "Output → input",
				Answer:   "Input → proses → output",
			},
			{
				QuizID:   7,
				Question: "Algoritma pemrograman terdiri dari tiga macam konstruksi, yaitu ...",
				OptionA:  "Algoritma sekuensial, algoritma percabangan, dan algoritma perulangan",
				OptionB:  "Algoritma struktural, algoritma percobaan, dan algoritma petualangan",
				OptionC:  "Algoritma skripsial, algoritma pertukaran, dan algoritma perrancangan",
				OptionD:  "Algoritma serentetan, algoritma percandaan dan algoritma perulangan",
				OptionE:  "Runtutan, Pemilihan, Perulangan",
				Answer:   "Algoritma sekuensial, algoritma percabangan, dan algoritma perulangan",
			},
			{
				QuizID:   7,
				Question: "Algoritma dengan prosedur yang berjalan dari satu proses ke proses berikutnya untuk mencapai hasil akhir. Contohnya, merebus air mentah hingga air matang disebut algoritma ...",
				OptionA:  "Algoritma Percabangan",
				OptionB:  "Algoritma Percobaan",
				OptionC:  "Algoritma Sekuensial",
				OptionD:  "Algoritma Pengulangan",
				OptionE:  "Algoritma Deskriptif",
				Answer:   "Algoritma Sekuensial",
			},
			{
				QuizID:   7,
				Question: "Algoritma yang menjalankan keputusan berdasarkan kondisi tertentu dengan dua atau lebih percabangan. Misalnya, jika nilai ujian lebih dari 75 maka hasilnya lulus ujian, disebut algoritma ...",
				OptionA:  "Algoritma Percabangan",
				OptionB:  "Algoritma Sekuensial",
				OptionC:  "Algoritma Pengulangan",
				OptionD:  "Algoritma Pencocokan",
				OptionE:  "Algoritma Percobaan",
				Answer:   "Algoritma Percabangan",
			},
		},
	}, {
		ID:          8,
		Name:        "BAB 8 Dampak Sosial Informatika",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652836/iquest/Rectangle-7_k8frvi.png",
		Description: "Mempelajari tentang dampak sosial informatika, baik positif maupun negatif, terhadap masyarakat.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   8,
				Question: "Seorang system analyst mempunyai tugas utama ...",
				OptionA:  "merubah sistem",
				OptionB:  "mengembangkan aplikasi dan database",
				OptionC:  "merancang sistem",
				OptionD:  "menginput data",
				OptionE:  "membuat program",
				Answer:   "merancang sistem",
			},
			{
				QuizID:   8,
				Question: "Berikut yang bukan merupakan dampak positif media sosial adalah ...",
				OptionA:  "Dapat bertemu dengan teman lama",
				OptionB:  "Dapat digunakan untuk berbagi berita",
				OptionC:  "Dapat digunakan untuk berjualan",
				OptionD:  "Dapat digunakan untuk mengumpulkan data pribadi pengguna lain",
				Answer:   "Dapat digunakan untuk mengumpulkan data pribadi pengguna lain",
			},
			{
				QuizID:   8,
				Question: "Perangkat lunak yang dilepas total oleh pembuatnya disebut ...",
				OptionA:  "Trial program",
				OptionB:  "Shareware",
				OptionC:  "Demo program",
				OptionD:  "Public domain",
				Answer:   "Public domain",
			},
			{
				QuizID:   8,
				Question: "Bagi seseorang yang ingin mengembangkan karirnya di dalam pengembangan komputasi awan, berikut adalah pilihan sertifikasi yang mesti ditempuh, kecuali....",
				OptionA:  "Microsoft - Certified Systems Engineer: Private Cloud (MCSE).",
				OptionB:  "Vmware - Certified Professional 6 - Data Center Virtualization.",
				OptionC:  "Google - Cloud Certifications.",
				OptionD:  "Amazon - Web Services Certified Solutions Architect (AWS-CSA).",
				Answer:   "Microsoft - SQL Server Certifications.",
			},
			{
				QuizID:   8,
				Question: "Anda adalah seorang pegawai pada sebuah perusahaan ternama. Anda sangat semangat dalam bekerja dan terkenal memiliki dedikasi tinggi dalam bekerja. Suatu hari, Anda tidak sengaja melakukan kesalahan fatal, sehingga merusak sistem dan database perusahaan. Bagaimana tindakan Anda?",
				OptionA:  "Berusaha memperbaikinya sendiri sebagai bentuk tanggung jawab kepada perusahaan.",
				OptionB:  "Memanggil ahli IT untuk memperbaiki kerusakan sistem dan database perusahaan tersebut.",
				OptionC:  "Melaporkan kejadian tersebut kepada atasan, dan bersedia untuk memberikan gaji Anda bulan ini sebagai bentuk tanggung jawab tanggungan biaya kerusakan sistem dan database perusahaan.",
				OptionD:  "Bertanya kepada teman tentang cara memperbaiki kerusakan sistem dan database perusahaan.",
				Answer:   "Memanggil ahli IT untuk memperbaiki kerusakan sistem dan database perusahaan tersebut.",
			},
			{
				QuizID:   8,
				Question: "Beberapa program komputer dudustribusikan dan memberikan lisensi untuk bebas mereproduksi program komputer menurut kondisi ...",
				OptionA:  "GPL",
				OptionB:  "Crack",
				OptionC:  "EULA",
				OptionD:  "License Agreement",
				Answer:   "GPL",
			},
			{
				QuizID:   8,
				Question: "Perhatikan beberapa kemudahan terkait teknologi informasi berikut.\n1) Produk lebih mudah dipasarkan melalui internet\n2) Usaha dapat dilakukan dengan modal yang lebih kecil\n3) Produk lebih muda diproduksi\n4) Ongkos produksi sebuah produk lebih murah\nTeknologi informasi memberikan kemudahan dalam membuka usaha. Penyebab yang benar ditunjukkan oleh nomor ...",
				OptionA:  "1) dan 2)",
				OptionB:  "2) dan 3)",
				OptionC:  "3) dan 4)",
				OptionD:  "4) dan 1)",
				Answer:   "1) dan 2)",
			},
			{
				QuizID:   8,
				Question: "Tanggung jawab dari keseluruhan perencanaan dan pelaksanaan sebuah proyek ada di pundak seorang...",
				OptionA:  "System analyst",
				OptionB:  "System Enginer",
				OptionC:  "Project Manager",
				OptionD:  "Programmer",
				OptionE:  "Staff EDP",
				Answer:   "Project Manager",
			},
			{
				QuizID:   8,
				Question: "Berikut adalah Bidang pekerjaan dengan spesialisasi dalam hal web developer, kecuali....",
				OptionA:  "Webmaster dan senior web developer",
				OptionB:  "front end developer dan web developer",
				OptionC:  "web administrator dan senior web administrator",
				OptionD:  "front end developer dan technical engineering",
				OptionE:  "web developer dan web administrator",
				Answer:   "front end developer dan technical engineering",
			},
			{
				QuizID:   8,
				Question: "Google  IT Support adalah salah satu sertifikasi IT bagi seseorang yang ingin mengembangkan dirinya dengan profesi sebagai....",
				OptionA:  "Developer",
				OptionB:  "Programmer",
				OptionC:  "HelpDesk",
				OptionD:  "Mobile Developer",
				Answer:   "HelpDesk",
			},
			{
				QuizID:   8,
				Question: "Pemegang hak atas program komputer menggunakan lisensi berjenis ...",
				OptionA:  "Product wrap",
				OptionB:  "Economic wrap",
				OptionC:  "Shink wrap",
				OptionD:  "Consumer wrap",
				Answer:   "Shink wrap",
			},
			{
				QuizID:   8,
				Question: "Teknologi berikut yang tidak memberikan peranan dalam meningkatkan interaksi sosial antara penggunanya adalah ...",
				OptionA:  "Line",
				OptionB:  "Microsoft Word",
				OptionC:  "Facebook",
				OptionD:  "WhatsApp",
				Answer:   "Microsoft Word",
			},
			{
				QuizID:   8,
				Question: "Perhatikan data berikut!\n1) Mendorong pengembangan program komputer secara bersama-sama\n2) Membuang program yang salah (bug)\n3) Mengenalkan karya turunan\n4) Mendistribusikian lisensi terbatas komersial\nBerdasarkan pernyataan di atas, gerakan open source disusun dengan tujuan ditunjukkan pada nomor ...",
				OptionA:  "1) dan 3)",
				OptionB:  "2) dan 4)",
				OptionC:  "1), 2) dan 3)",
				OptionD:  "2) dan 3)",
				Answer:   "1), 2) dan 3)",
			},
			{
				QuizID:   8,
				Question: "Profesi berikut yang bukan termasuk profesi baru dengan memanfaatkan media sosial adalah ...",
				OptionA:  "Food blogger",
				OptionB:  "Gamer",
				OptionC:  "Selebgram",
				OptionD:  "Pembuat caption instagram",
				Answer:   "Gamer",
			},
			{
				QuizID:   8,
				Question: "Programmer dan Developer adalah dua jenis pekerjaan dalam bidang informatika yang berbeda. Pernyataan yang kurang tepat tentang keduanya di bawah ini adalah....",
				OptionA:  "Setiap programmer yang hebat sudah dipastikan bisa menjadi seorang developer",
				OptionB:  "Baik programmer maupun developer memiliki tugas yang berhubungan dengan coding",
				OptionC:  "Seorang developer adalah seorang programmer",
				OptionD:  "Developer memiliki salah satu tugasnya adalah Mendesain perangkat lunak",
				OptionE:  "Developer memiliki salah satu tugasnya adalah melakukan pengembangan sistem",
				Answer:   "Setiap programmer yang hebat sudah dipastikan bisa menjadi seorang developer",
			},
			{
				QuizID:   8,
				Question: "Apa yang dimaksud dengan abacus dalam sejarah perkembangan komputer?",
				OptionA:  "Sebuah komputer pertama",
				OptionB:  "Sebuah tipe komputer mini",
				OptionC:  "Sebuah mesin hitung manual kuno",
				OptionD:  "Sebuah program komputer",
				Answer:   "Sebuah mesin hitung manual kuno",
			},
			{
				QuizID:   8,
				Question: "Siapa yang merupakan pemrogram pertama dalam sejarah komputer?",
				OptionA:  "Charles Babbage",
				OptionB:  "Ada Lovelace",
				OptionC:  "Alan Turing",
				OptionD:  "Al-Khawarizmi",
				OptionE:  "Steve Jobs",
				Answer:   "Ada Lovelace",
			},
			{
				QuizID:   8,
				Question: "Apa yang menjadi dasar pengembangan bahasa-bahasa pemrograman dan teori otomata?",
				OptionA:  "Mesin Turing",
				OptionB:  "Abacus",
				OptionC:  "Compiler",
				OptionD:  "Mesin abstrak",
				Answer:   "Mesin Turing",
			},
			{
				QuizID:   8,
				Question: "Bagaimana komputer berevolusi seiring waktu?",
				OptionA:  "Dengan tetap menggunakan model abstrak",
				OptionB:  "Dengan membuang model abstrak",
				OptionC:  "Dengan tidak mengalami perkembangan",
				OptionD:  "Dengan mengurangi kompleksitas",
				Answer:   "Dengan tetap menggunakan model abstrak",
			},
			{
				QuizID:   8,
				Question: "Apa manfaat mempelajari sejarah perkembangan komputer?",
				OptionA:  "Untuk mengurangi perkembangan teknologi",
				OptionB:  "Untuk mengabaikan keberhasilan dan kegagalan",
				OptionC:  "Untuk memperlambat penemuan mesin-mesin baru",
				OptionD:  "Untuk belajar dari masa lalu dan mempercepat penemuan mesin-mesin baru",
				Answer:   "Untuk belajar dari masa lalu dan mempercepat penemuan mesin-mesin baru",
			},
		},
	}, {
		ID:          9,
		Name:        "BAB 9 Praktik Lintas Bidang Informatika",
		Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721654644/iquest/Rectangle-9_ytvkks.png",
		Description: "Mempelajari tentang praktik lintas bidang informatika yang melibatkan berbagai aspek informatika dalam kehidupan sehari-hari.",
		ClassID:     1,
		Questions: []entity.QuestionQuiz{
			{
				QuizID:   9,
				Question: "Apa contoh dampak sosial dari informatika?",
				OptionA:  "Peningkatan polusi",
				OptionB:  "Memfasilitasi jaringan social",
				OptionC:  "Memudahkan proses bisnis",
				OptionD:  "Penurunan jumlah pekerjaan",
				Answer:   "Memfasilitasi jaringan social",
			},
			{
				QuizID:   9,
				Question: "Teknologi informasi dapat memperpanjang durasi waktu seseorang mengerjakan tugasnya. Apa nama fenomena ini?",
				OptionA:  "Pasar pasang",
				OptionB:  "Ingatan social",
				OptionC:  "Ekonomi kreatif",
				OptionD:  "Disutansi",
				Answer:   "Disutansi",
			},
			{
				QuizID:   9,
				Question: "Bagaimana dampak sosial informatika terhadap ekonomi dunia?",
				OptionA:  "Mengakibatkan inflasinya",
				OptionB:  "Meningkatkan tingkat keuntungan",
				OptionC:  "Meningkatkan kualitas hidup",
				OptionD:  "Meningkatkan persaingan",
				Answer:   "Meningkatkan kualitas hidup",
			},
			{
				QuizID:   9,
				Question: "Teknologi informasi memiliki dampak sosial khusus terhadap dunia perdagangan. Apakah nama fenomena ini?",
				OptionA:  "Pasar pasang",
				OptionB:  "Ekonomi informasi",
				OptionC:  "Peringatan social",
				OptionD:  "Disutansi",
				Answer:   "Ekonomi informasi",
			},
			{
				QuizID:   9,
				Question: "Bernapas udara bersih adalah salah satu hasil dari teknologi informasi. Bagaimana dampak sosial informatika ini?",
				OptionA:  "Meningkatkan polusi",
				OptionB:  "Mengurangi biaya produksi",
				OptionC:  "Meningkatkan kualitas udara",
				OptionD:  "Mengurangi efisiensi",
				Answer:   "Meningkatkan kualitas udara",
			},
			{
				QuizID:   9,
				Question: "Manfaat teknologi informasi bagi anak-anak adalah membantu…",
				OptionA:  "Mengajar mereka tentang teknologi",
				OptionB:  "Membuat mereka terlalu tergantung pada teknologi",
				OptionC:  "Memudahkan pembelajaran melalui internet",
				OptionD:  "Memonitor mereka setiap saat",
				Answer:   "Memudahkan pembelajaran melalui internet",
			},
			{
				QuizID:   9,
				Question: "Di bawah ini adalah dampak sosial yang terkait dengan informatika selain meningkatkan konsep produktivitas, autonomi, dan jaringan. Apa nama fenomena ini?",
				OptionA:  "Automasi",
				OptionB:  "Proteksi data",
				OptionC:  "Persahabatan mesin",
				OptionD:  "Pemanfaatan data",
				Answer:   "Automasi",
			},
			{
				QuizID:   9,
				Question: "Di bawah ini adalah dampak sosial teknologi informasi untuk pengolahan data. Apa nama fenomena ini?",
				OptionA:  "Otomatisasi",
				OptionB:  "Penerapan mesin",
				OptionC:  "Pemanfaatan data",
				OptionD:  "Teknik pengenalan wajah",
				Answer:   "Pemanfaatan data",
			},
			{
				QuizID:   9,
				Question: "Teknologi informasi telah membantu mengurangi biaya produksi di seluruh dunia. Bagaimana cara teknologi informasi membantu ini?",
				OptionA:  "Dengan mengurangi manusia kerja",
				OptionB:  "Dengan mengurangi peralatan produksi",
				OptionC:  "Dengan meningkatkan efisiensi bisnis",
				OptionD:  "Dengan mengurangi pemborosan",
				Answer:   "Dengan meningkatkan efisiensi bisnis",
			},
			{
				QuizID:   9,
				Question: "Apa dampak sosial teknologi informasi untuk bisnis?",
				OptionA:  "Memungkinkan otomasi",
				OptionB:  "Meningkatkan tingkat kegagalan",
				OptionC:  "Menciptakan lapangan pekerja baru",
				OptionD:  "Memperlambat proses e-commerce",
				Answer:   "Memungkinkan otomasi",
			},
			{
				QuizID:   9,
				Question: "Apa yang dimaksud dengan lintas bidang informatika ?",
				OptionA:  "Kelompok studi yang melibatkan aspek teknikal dan ilmu pengetahuan komputer.",
				OptionB:  "Kumpulan teknologi yang berfokus pada algoritme komputasi.",
				OptionC:  "Pendekatan secara sistematis dalam memecahkan masalah komputasi.",
				OptionD:  "Pendekatan interdisipliner dari bidang-bidang terkait.",
				Answer:   "Pendekatan interdisipliner dari bidang-bidang terkait.",
			},
			{
				QuizID:   9,
				Question: "Apakah tugas utama dari lintas bidang informatika ?",
				OptionA:  "Solusi teknis untuk berbagai jenis masalah.",
				OptionB:  "Menggabungkan berbagai riset dan aplikasi komputasi.",
				OptionC:  "Merumuskan teknologi yang bermanfaat dengan cara interdisiplin.",
				OptionD:  "Pengembangan infrastruktur komputasi di seluruh dunia.",
				Answer:   "Merumuskan teknologi yang bermanfaat dengan cara interdisiplin.",
			},
			{
				QuizID:   9,
				Question: "Di antara berbagai disiplin informatika, aplikasi grafika termasuk",
				OptionA:  "Sistem jaringan",
				OptionB:  "Sistem basis data",
				OptionC:  "Animasi 3D",
				OptionD:  "Sistem operasi",
				Answer:   "Animasi 3D",
			},
			{
				QuizID:   9,
				Question: "Apa yang dimaksud dengan teknologi lintas bidang ?",
				OptionA:  "Teknologi untuk menerapkan dampak dari riset sains secara interdisiplin.",
				OptionB:  "Teknologi yang menggabungkan berbagai teori informatika dalam satu proyek.",
				OptionC:  "Teknologi yang menggunakan berbagai teknik pemrograman dalam satu proyek.",
				OptionD:  "Teknologi untuk meningkatkan kinerja berbagai perangkat lunak.",
				Answer:   "Teknologi untuk menerapkan dampak dari riset sains secara interdisiplin.",
			},
			{
				QuizID:   9,
				Question: "Bidang ilmu apa yang dapat mengambil manfaat dari lintas bidang informatika ?",
				OptionA:  "Fisika",
				OptionB:  "Matematika",
				OptionC:  "Kimia",
				OptionD:  "Biologi",
				Answer:   "Fisika, Matematika, Kimia, Biologi",
			},
			{
				QuizID:   9,
				Question: "Apakah yang dimaksud dengan manajemen lintas bidang informatika ?",
				OptionA:  "Penggunaan berbagai teknik untuk memecahkan masalah kompleks.",
				OptionB:  "Teknik pemrograman untuk meningkatkan kinerja komputer.",
				OptionC:  "Menghubungkan kemampuan bersama dari berbagai disiplin ilmu informatika.",
				OptionD:  "Pengembangan infrastruktur komputasi di seluruh dunia.",
				Answer:   "Menghubungkan kemampuan bersama dari berbagai disiplin ilmu informatika.",
			},
			{
				QuizID:   9,
				Question: "Tata cara manajemen lintas bidang informatika termasuk",
				OptionA:  "Memahami aspek teknis dan non-teknis dari proyek.",
				OptionB:  "Memanfaatkan kemampuan teknis para ahli dari berbagai bidang.",
				OptionC:  "Pemecahan masalah dengan menggunakan bahasa pemrograman.",
				OptionD:  "Penggunaan berbagai teknologi untuk menyelesaikan permasalahan.",
				Answer:   "Memahami aspek teknis dan non-teknis dari proyek, Memanfaatkan kemampuan teknis para ahli dari berbagai bidang, Penggunaan berbagai teknologi untuk menyelesaikan permasalahan.",
			},
			{
				QuizID:   9,
				Question: "Apa yang dimaksud dengan lingkungan lintas bidang informatika ?",
				OptionA:  "Pendekatan secara sistematis untuk memecahkan masalah komputasi.",
				OptionB:  "Suatu komunitas yang menggabungkan berbagai ilmu dan teknologi.",
				OptionC:  "Pendekatan interdisipliner dari bidang-bidang terkait.",
				OptionD:  "Teknik kolaboratif untuk menerapkan dan mengembangkan teknologi.",
				Answer:   "Suatu komunitas yang menggabungkan berbagai ilmu dan teknologi.",
			},
			{
				QuizID:   9,
				Question: "Manfaat utama dari lintas bidang informatika adalah",
				OptionA:  "Raihan hasil yang lebih efisien dan lebih cepat.",
				OptionB:  "Penyelesaian masalah secara lebih akurat dan lebih tepat.",
				OptionC:  "Penggunaan berbagai teknik pemrograman untuk meningkatkan kinerja.",
				OptionD:  "Kombinasi kemampuan dari berbagai disiplin ilmu untuk menganalisis masalah.",
				Answer:   "Kombinasi kemampuan dari berbagai disiplin ilmu untuk menganalisis masalah.",
			},
			{
				QuizID:   9,
				Question: "Berikut ini merupakan bab kerja yang harus diikuti dalam lintas bidang informatika, kecuali",
				OptionA:  "Analisis masalah",
				OptionB:  "Konsultasi",
				OptionC:  "Pengembangan Software",
				OptionD:  "Perancangan Grafis",
				Answer:   "Perancangan Grafis",
			},
		},
	},
	}

	return quizzes
}

func ClassSeed() []entity.Class {
	id, _ := uuid.Parse("b3f1f4c6-0b5d-4b0d-8e2e-6e0c1d4c5d9d")

	classes := []entity.Class{{
		Name:      "Informatika",
		TeacherID: id,
		Goal:      "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1720242761/iquest/jsal4xbga8q8cjhc74w3.pdf",
	}}

	return classes
}

func UserSeed() []entity.User {
	passTeacher, _ := bcrypt.HashPassword("teacher123")
	passStudent, _ := bcrypt.HashPassword("student123")
	idTeacher, _ := uuid.Parse("b3f1f4c6-0b5d-4b0d-8e2e-6e0c1d4c5d9d")
	idStudent, _ := uuid.Parse("2aa2a2b6-63b3-4a7d-b0b8-0a7756ff884f")

	users := []entity.User{{
		ID:       idTeacher,
		Name:     "Teacher",
		Role:     entity.RoleTeacher,
		Password: passTeacher,
	}, {
		ID:       idStudent,
		Name:     "Student",
		Role:     entity.RoleStudent,
		Password: passStudent,
	},
	}

	return users
}

func VideoSeed() []entity.Video {
	videos := []entity.Video{
		{
			ID:          1,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652831/iquest/Rectangle_ddwqjn.png",
			Video:       "https://youtu.be/IB5Y9FJnVXQ?si=-CY30r7SWJFcr54F",
			Title:       "BAB 1 Informatika dan Keterampilan Generik",
			Description: "Video pembelajaran mengenai dasar-dasar informatika dan keterampilan generik yang diperlukan untuk memahami materi informatika.",
		},
		{
			ID:          2,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652833/iquest/Rectangle-1_yfrcj3.png",
			Video:       "https://youtu.be/ol0G_lrgNBI?si=9RhvI7I6r9LLw8NM",
			Title:       "BAB 2 Berpikir Komputasional",
			Description: "Video pembelajaran tentang berpikir komputasional dan cara memecahkan masalah secara logis dan efisien.",
		},
		{
			ID:          3,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652834/iquest/Rectangle-2_v3dbzb.png",
			Video:       "https://youtu.be/FIGAQSXZS9o?si=iWajTTajdHYt4rBP",
			Title:       "BAB 3 Teknologi Informasi dan Komunikasi",
			Description: "Video pembelajaran mengenai teknologi informasi dan komunikasi, serta peranannya dalam kehidupan sehari-hari.",
		},
		{
			ID:          4,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652836/iquest/Rectangle-3_f5gf5a.png",
			Video:       "https://youtu.be/M_qL2Rfd_yw?si=h1AO9shiO5aWSu_l",
			Title:       "BAB 4 Sistem Komputer",
			Description: "Video pembelajaran tentang sistem komputer, komponen-komponennya, dan cara kerjanya.",
		},
		{
			ID:          5,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652832/iquest/Rectangle-4_hcuhke.png",
			Video:       "https://youtu.be/c6RG-l75_Qo?si=wlbi74ZCvNyIjNqa",
			Title:       "BAB 5 Jaringan Komputer dan Internet",
			Description: "Video pembelajaran mengenai jaringan komputer dan internet, termasuk cara kerjanya dan jenis-jenis jaringannya.",
		},
		{
			ID:          6,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652834/iquest/Rectangle-5_ktyjon.png",
			Video:       "https://youtu.be/L9wlcDVrO8E?si=uLnKNCO5053aV98X",
			Title:       "BAB 6 Analisis Data",
			Description: "Video pembelajaran tentang analisis data, teknik-teknik analisis, dan penerapannya dalam berbagai bidang.",
		},
		{
			ID:          7,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652837/iquest/Rectangle-6_kzxfgb.png",
			Video:       "https://youtu.be/-iGMZEsSEG8?si=0t2fsGBw_CmnoiB6",
			Title:       "BAB 7 Algoritma dan Pemrograman",
			Description: "Video pembelajaran mengenai algoritma dan pemrograman, termasuk cara menulis kode program yang efisien.",
		},
		{
			ID:          8,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721652836/iquest/Rectangle-7_k8frvi.png",
			Video:       "https://youtu.be/wawDQTJCsBg?si=-f6v-n_3bz96rVYy",
			Title:       "BAB 8 Dampak Sosial Informatika",
			Description: "Video pembelajaran tentang dampak sosial informatika, baik positif maupun negatif, terhadap masyarakat.",
		},
		{
			ID:          9,
			ClassID:     1,
			Image:       "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1721654644/iquest/Rectangle-9_ytvkks.png",
			Video:       "https://youtu.be/bXyRcqHnZeA?si=Ex-dRPjQWauOMtmc",
			Title:       "BAB 9 Praktika Lintas Bidang Informatika",
			Description: "Video pembelajaran mengenai praktika lintas bidang informatika dan aplikasi praktis dalam kehidupan sehari-hari.",
		},
	}

	return videos
}

func CourseSeed() []entity.Course {
	courses := []entity.Course{
		{
			Title:       "Informatika",
			Description: "Materi Infomatika",
			ClassID:     1,
			Course:      "https://res.cloudinary.com/dcvnwpyd9/image/upload/v1720244441/iquest/i3l195tfithqpdgolfqd.pdf",
		},
	}

	return courses
}

func MigrateSeed(db *gorm.DB) error {
	quizzes := QuizSeed()
	classes := ClassSeed()
	users := UserSeed()
	videos := VideoSeed()
	courses := CourseSeed()

	var count int64
	if err := db.Model(&entity.User{}).Count(&count).Error; err != nil {
		return err
	}

	if count == 0 {
		if err := db.CreateInBatches(users, len(users)).Error; err != nil {
			return err
		}
	}

	if err := db.Model(&entity.Class{}).Count(&count).Error; err != nil {
		return err
	}

	if count == 0 {
		if err := db.CreateInBatches(classes, len(classes)).Error; err != nil {
			return err
		}
	}

	if err := db.Model(&entity.Quiz{}).Count(&count).Error; err != nil {
		return err
	}

	if count == 0 {
		if err := db.CreateInBatches(quizzes, len(quizzes)).Error; err != nil {
			return err
		}
	}

	if err := db.Model(&entity.Video{}).Count(&count).Error; err != nil {
		return err
	}

	if count == 0 {
		if err := db.CreateInBatches(videos, len(videos)).Error; err != nil {
			return err
		}
	}

	if err := db.Model(&entity.Course{}).Count(&count).Error; err != nil {
		return err
	}

	if count == 0 {
		if err := db.CreateInBatches(courses, len(courses)).Error; err != nil {
			return err
		}
	}

	return nil
}
